version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100m" 
    max-file: "100"   

services:
  react-app:
    container_name: docker-test-FE
    restart: always 
    image: hs60/docker-test1:latest
    logging: *default-logging  
    network_mode: "host"
    env_file:
      - .env 
    volumes:
     - ./uploads:/usr/share/nginx/html/application-files
     - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    container_name: docker-test-BE
    image: hs60/docker-test2:latest  
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads 
    restart: always  
    logging: *default-logging
    network_mode: "host"
#     depends_on:
#       - postgres_db

#   postgres_db:
#     image: postgres:16.3
#     container_name: postgres-db
#     restart: always
#     volumes:
#       - db-data:/var/lib/postgresql/data
#       # - ./initdb.d:/docker-entrypoint-initdb.d
#       # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
#     environment:
#       - POSTGRES_DB=${DB_NAME}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_HOST_AUTH_METHOD=md5
#       - POSTGRES_INITDB_ARGS=--auth=md5
#     logging: *default-logging
#     network_mode: "host"
#     env_file:
#       - .env

# volumes:
#   db-data:    
